name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "/clinica-salomao/src"
        remoteDir: "\\windows-pd-0001.fs.locaweb.com.br\WNFS-0002\clinicaesteticas1\web"
